### PR TITLE
Use an ordered broadcast to ensure only a single pacemaker instance ever schedules heartbeats

### PR DESCRIPTION
**Pull request by esoxjem**

### CODE REVIEW

**Comment by raveeshbhalla** [comment]
Hey @esoxjem can you provide details regarding the logic you've used to resolve this issue over here as well. Will go through the pull request tomorrow in detail.

**Comment by esoxjem** [comment]
Whenever Pacemaker schedules a linear or exponential heartbeat, an <b>ordered broadcast</b> is sent across the system. Whichever `Scheduler`instance in any app that receives this broadcast <b>first</b> with schedule the alarm accordingly and stop further propagation to other receivers by calling `abortBroadcast()`. This ensures only one app will send heartbeats.

**Comment by esoxjem** [comment]
This solution is flawed. Closing.

**Comment by PuneetKohli** [comment]
Hi, could you discuss the flaws? Would be great for learning and understanding :)

**Comment by esoxjem** [comment]
This only allows one instance of Pacemaker to schedule heartbeats hence overriding intervals scheduled by other apps. Different apps may want to use different scheduling. Also, this does not handle multiple concurrent broadcasts. 

It also doesn't take into consideration the Doze mode in Android M. Pacemaker will seize to function normally on Marshmallow.

In my opinion, this should be a system service and shouldn't be handled by the application layer.

**Comment by raveeshbhalla** [comment]
Ideally, yes this should be handled at OS/Play Services layer, but the entire reason for Pacemaker's existence is that Google hasn't shown this to be a priority :)

**Comment by PuneetKohli** [comment]
Was going to say the same as Raveesh.

The best we can do with an app is have only 1 instance send the broadcast. Now the questions to be answered are-
1. Which instance should send it
2. What logic should be used to determine the same
3. How do make sure 1 and 2 take place 

Also, with respect to your point on scheduling - An Exponential schedule should continue it's broadcast as is, whereas the "polling" of broadcasts should only be done in the case of Linear broadcasts in my opinion. The reason for this is that Exponential Broadcasts will automatically kill themselves after a set period of time anyways. But you may argue that an Exponential Broadcast need not be executed at all, if a Linear Broadcast is already running on the phone, to which I concur.

The algorithm I've suggested only allows the instance with minimum time (delay) to run on the given device. For that, on Schedule of Linear, we determine whether we have the minimum time or not, If we do - we go forward with scheduling it, else we just ignore straight off the bat. Once scheduled we check if we should broadcast (By checking whether anyone else has updated the minimum value, in which case we check again and repeat the process). If we don't have the minimum value, we just cancel.

Exponential requests become a bit easier to handle but a little tricky in the logic.
If there are no linear requests on the system - we let all the exponential requests go through, as they all have varying times and they all die out after a while anyways. (Accommodated for this in commit #2). There may be some overlap here and could cause minor hiccups in the phone battery, but as it is exponential, they are bound to die out eventually and depend on the user's usage of the Pacemaker carrying apps.
In the case there is an existing Linear request on the system, we just ignore the Exponential request as a linear request is most probably going to have a shorter average delay time. This can be mathematically proved, but intuitively also, it makes sense.

**Pull request closed without merging**
